name: allure-report

on:
  pull_request:
    types: [opened, reopened]

jobs:
  allure-pr:
    name: Check Allure Report Action on Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        #id: allure-report
        with:
          allure_results: allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history
          keep_reports: 1